Update the overview to get the numbering/bullet points right
decentralized-identity/trustdidweb-info pull request #7
Opened 2024-10-21 16:19 UTC by swcurran

Signed-off-by: Stephen Curran <swcurran@gmail.com>

2024-10-21 16:22 UTC, swcurran commented
Tweaks @martipos PR:

- removes the leading "> " on the overview (I don't think it should be "quoted" text, which is what that implies).
- Always uses 4 spaces for indenting bullet levels.  GitHub markdown only needs 2, but the Markdown that mkdocs uses REQUIRES 4.
- Some editorial tweaks to the overview - particularly around `entryHash` and `versionId`

2024-12-04 00:11 UTC, PatStLouis requested changes

2024-12-04 00:11 UTC, PatStLouis commented on docs/overview.md
> +        - `proofPurpose` := `assertionMethod`
```suggestion
        - `type` := `DataIntegrityProof`
        - `cryptosuite` := `eddsa-jcs-2022`
        - `proofPurpose` := `assertionMethod`
```

2024-12-04 00:14 UTC, swcurran commented on docs/overview.md
> +        - `proofPurpose` := `assertionMethod`
Fixed.

2024-12-04 00:15 UTC, PatStLouis approved these changes

2024-12-04 00:16 UTC, merged

2024-12-04 00:16 UTC, swcurran commented
Thx!